// Suggestions only: a candidate may add any skill. The list is static, not derived from other candidates' data.
export const skillSuggestions: readonly string[] = [
  "Arc welding",
  "Assembly line work",
  "Baking",
  "Bar service",
  "Bricklaying",
  "Cabinet making",
  "Car mechanics",
  "Carpentry",
  "Cashier work",
  "Child care",
  "Cleaning",
  "CNC machine operation",
  "Concrete finishing",
  "Cooking",
  "Crane operation",
  "Customer service",
  "Data entry",
  "Delivery driving",
  "Diesel mechanics",
  "Drywall installation",
  "Electrical installation",
  "Electrical maintenance",
  "Elderly care",
  "Excavator operation",
  "First aid",
  "Floor tiling",
  "Food preparation",
  "Forklift operation",
  "Gardening",
  "Gas welding",
  "Glazing",
  "Hairdressing",
  "Heavy goods vehicle driving",
  "Home care",
  "Housekeeping",
  "HVAC installation",
  "Inventory management",
  "Kitchen assistance",
  "Landscaping",
  "Machine maintenance",
  "Masonry",
  "Metal fabrication",
  "MIG welding",
  "Painting and decorating",
  "Patient care",
  "Pipe fitting",
  "Plastering",
  "Plumbing",
  "Quality control",
  "Reading technical drawings",
  "Reception work",
  "Refrigeration repair",
  "Roofing",
  "Safety inspection",
  "Scaffolding",
  "Sewing",
  "Sheet metal work",
  "Steel fixing",
  "Stock replenishment",
  "TIG welding",
  "Tailoring",
  "Team leadership",
  "Truck loading",
  "Warehouse operation",
  "Waiting tables",
  "Welding",
  "Window cleaning",
  "Wiring",
];
